.TH yMODE 7 2010-oct "linux" "decision rationale, objectives, and overview"

.SH NAME
.B yMODE
\- shared yVIKEYS (vi/vim) mode tracking and control

.SH PATRON
.B zeus-xenia
(guest-friend) protector of travellers, guests, and hosts

.SH IMAGERY
greek god disguised as a normal traveller seeking shelter

.SH SUMMARY
.B yMODE
is a simple, shared, well-tested library which allows applications to
safely initialize, configure, and navigate the universal heatherly vi/vim-ish
modal system
.B (yVIKEYS).

.SH DOCUMENTATION FILES
.nf
yMODE (3)          interfacing applications with library
.nf
.B yMODE (7)··········decision rationale, objectives, and overview

.SH A) DEFINITION
modes are everywhere, but most people do not recognize them.  when a keyboard
key means one thing on one screen and something else on another, that is modal.
most of these variation appear random and users take to note.

modes and modal application use is a keyboard-centric way of operating which
allows high efficency at the cost of a steeper learning curve.  i have accepted
the vi/vim model as directionally correct and most of its concepts as
absolutely manditory in power-user environments.


